#!/bin/bash

# E2EE Chat App - Startup Script
# Usage: ./start.sh
#
# IMPORTANT: This script preserves all database volumes on restart.
# Data in PostgreSQL, Redis, MongoDB, and MinIO persists across stop/start cycles.
# Credentials are loaded from .env file (auto-generated by setup-security.sh)

set -euo pipefail

COMPOSE_CMD=(docker compose -f docker-compose.yml)

# Check prerequisites
if ! docker compose version >/dev/null 2>&1; then
	echo "❌ docker compose (v2) is required but not available"
	exit 1
fi

if [ ! -f .env ]; then
	echo "❌ .env file not found! Run ./setup-security.sh first"
	exit 1
fi

# Load environment variables
set -a
source .env
set +a

sudo -v

echo "🚀 Starting E2EE Chat App..."
echo "ℹ️  Database volumes are PRESERVED across restarts"
echo "🔐 Loading credentials from .env"

# Stop containers WITHOUT removing volumes (use stop instead of down)
echo "Stopping existing containers (if any)..."
sudo "${COMPOSE_CMD[@]}" stop 2>/dev/null || true

# Remove orphaned containers only (not volumes!)
echo "Cleaning up orphaned containers..."
sudo docker ps -a --filter "name=^/e2ee_" --format '{{.ID}}' | xargs -r sudo docker rm -f 2>/dev/null || true

# Build services to ensure latest images
echo "Building service images..."
sudo "${COMPOSE_CMD[@]}" build --no-cache

# Start postgres first and wait for health check
echo "Starting PostgreSQL first..."
sudo "${COMPOSE_CMD[@]}" up -d postgres

echo "Waiting for PostgreSQL to become healthy..."
for i in {1..60}; do
	if sudo "${COMPOSE_CMD[@]}" exec -T postgres pg_isready -U "${POSTGRES_USER:-postgres}" >/dev/null 2>&1; then
		echo "✅ PostgreSQL is ready"
		break
	fi

	if [ "$i" -eq 60 ]; then
		echo "❌ PostgreSQL did not become ready in time"
		sudo "${COMPOSE_CMD[@]}" logs postgres
		exit 1
	fi

	echo "   Waiting... ($i/60)"
	sleep 2
done

# Verify auth_db exists (schema will be auto-created by init-db.sql)
echo "Verifying auth_db schema..."
sudo "${COMPOSE_CMD[@]}" exec -T postgres psql -U "${POSTGRES_USER:-postgres}" -d auth_db -c "\\dt" 2>/dev/null || {
	echo "⚠️  Schema not found, letting init script create it..."
}

# Start all remaining services
echo "Starting remaining services (Redis, MongoDB, MinIO, API Gateway, services)..."
sudo "${COMPOSE_CMD[@]}" up -d

# Wait for all services to be healthy
echo "Waiting for all services to become ready..."
sleep 5

echo ""
echo "✅ All services are running!"
echo ""
echo "📍 Internal Service URLs (container network):"
echo "   API Gateway:  http://e2ee_api_gateway:8000"
echo "   Auth Service:  http://e2ee_auth_service:8001"
echo "   Chat Service:  http://e2ee_chat_service:8002"
echo "   Message Service: http://e2ee_message_service:8003"
echo "   Media Service:  http://e2ee_media_service:8004"
echo ""
echo "📍 External URLs (accessible from host):"
echo "   NGINX:        http://localhost (port 80)"
echo "   HTTPS:        https://localhost (port 443, if configured)"
echo "   API Gateway:  http://localhost:8000"
echo ""
echo "🔐 Credentials loaded from .env:"
echo "   PostgreSQL:   User '${POSTGRES_USER:-postgres}' with secure password"
echo "   Redis:        Password-protected (internal only)"
echo "   MongoDB:      User '${MONGO_USER:-admin}' (internal only)"
echo ""
echo "📊 Database Status:"
sudo "${COMPOSE_CMD[@]}" exec -T postgres psql -U "${POSTGRES_USER:-postgres}" -d auth_db -c "SELECT 'Users' as table_name, count(*) as count FROM users UNION ALL SELECT 'Friends', count(*) FROM friends UNION ALL SELECT 'Devices', count(*) FROM devices;" 2>/dev/null || echo "   (Database initializing...)"
echo ""
echo "📝 Useful Commands:"
echo "   View logs:     sudo docker compose logs -f"
echo "   Stop services: ./stop.sh"
echo "   Check health:  sudo docker compose ps"
echo "   Rebuild:       sudo docker compose build --no-cache"
echo ""
echo "⚠️  SECURITY REMINDERS:"
echo "   - .env file contains sensitive credentials"
echo "   - DO NOT commit .env to git"
echo "   - Database ports are NOT exposed to internet"
echo "   - Rotate credentials every 90 days"
echo "   - See SECURITY.md for detailed security info"